# Generated by Django 5.1.7 on 2025-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='question_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
