# Generated by Django 5.1.7 on 2025-04-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subgoal_option1_subgoal_option2_subgoal_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoal',
            name='rating',
        ),
        migrations.CreateModel(
            name='SubGoalUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subgoal')},
            },
        ),
    ]
