# Generated by Django 5.1.7 on 2025-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_subgoal_rating_subgoaluserrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoal',
            name='option1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
