# Generated by Django 5.1.7 on 2025-04-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_subgoal_option1_alter_subgoal_option2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgoaluserrating',
            options={'verbose_name': 'Alt Hedef Değerlendirmesi', 'verbose_name_plural': 'Alt Hedef Değerlendirmeleri'},
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 1'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 2'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 3'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 4'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='option5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 5'),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='question_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soru Puanı'),
        ),
    ]
