# Generated by Django 5.1.7 on 2025-04-19 16:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_subgoaluserrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoaluserrating',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_proof_upload_path, verbose_name='Kanıt Dosyası'),
        ),
    ]
