# Generated by Django 5.1.7 on 2025-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subgoaluserrating_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoaluserrating',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='subgoal_uploads', verbose_name='Kanıt Dosyası'),
        ),
    ]
