# Generated by Django 5.1.7 on 2025-04-19 16:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subgoaluserrating_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoaluserrating',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subgoaluserrating',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_proof_upload_path, verbose_name='Kanıt Dosyası'),
        ),
    ]
