# Generated by Django 5.1.7 on 2025-04-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_subgoaluserrating_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoaluserrating',
            name='proof_file',
        ),
    ]
