# Generated by Django 5.1.7 on 2025-04-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_subgoaluserrating_proof_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgoaluserrating',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
