# Generated by Django 5.1.7 on 2025-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_created_at_subgoaluserrating_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgoaluserrating',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
