# Generated by Django 5.1.7 on 2025-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_updated_at_subgoaluserrating_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Hedef', 'verbose_name_plural': 'Hedefler'},
        ),
        migrations.AlterModelOptions(
            name='subgoal',
            options={'verbose_name': 'Alt Hedef', 'verbose_name_plural': 'Alt Hedefler'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Üniversite', 'verbose_name_plural': 'Üniversiteler'},
        ),
        migrations.AddField(
            model_name='subgoaluserrating',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subgoaluserrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
