# Generated by Django 5.1.7 on 2025-04-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_options_alter_goal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgoaluserrating',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
