# Generated by Django 5.1.7 on 2025-04-21 18:11

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_updated_ad_subgoaluserrating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoaluserrating',
            name='pdf_upload',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Kanıt PDF'),
        ),
    ]
