# Generated by Django 5.1.7 on 2025-04-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_subgoaluserrating_pdf_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoal',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option5',
        ),
        migrations.CreateModel(
            name='SubGoalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Seçenek Metni')),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.subgoal')),
            ],
            options={
                'verbose_name': 'Alt Hedef Seçeneği',
                'verbose_name_plural': 'Alt Hedef Seçenekleri',
            },
        ),
    ]
