# Generated by Django 5.1.7 on 2025-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_subgoal_option1_remove_subgoal_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoaloption',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Değer'),
        ),
    ]
