# Generated by Django 5.1.7 on 2025-04-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subgoaloption_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoaloption',
            name='value',
        ),
    ]
