# Generated by Django 5.1.7 on 2025-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_subgoaloption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='option1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 1'),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 2'),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 3'),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 4'),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='option5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seçenek 5'),
        ),
        migrations.DeleteModel(
            name='SubGoalOption',
        ),
    ]
