# Generated by Django 5.1.7 on 2025-04-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_subgoal_option1_subgoal_option2_subgoal_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoal',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='option5',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.subgoal')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
            },
        ),
    ]
