# Generated by Django 5.1.7 on 2025-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_rating_subgoaluserrating_selected_option_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id'], 'verbose_name': 'Seçenek', 'verbose_name_plural': 'Seçenekler'},
        ),
    ]
