# Generated by Django 5.1.7 on 2025-04-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_option_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgoal',
            options={},
        ),
    ]
