# Generated by Django 5.1.7 on 2025-04-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_subgoal_option1_remove_subgoal_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
