# Generated by Django 5.1.7 on 2025-04-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoaluserrating',
            name='total_max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subgoaluserrating',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
