# Generated by Django 5.1.7 on 2025-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_subgoaluserrating_total_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='is_numeric',
            field=models.BooleanField(default=False),
        ),
    ]
