# Generated by Django 5.1.7 on 2025-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_subgoal_is_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='requires_proof',
            field=models.BooleanField(default=False),
        ),
    ]
